# # Do not change version. This is the version of aws buildspec, not the version of your buldspec file.There is nothing to change here.
# version: 0.2
# phases:
#   install:
#     runtime-versions:
#       nodejs: 10
#   pre_build:
#     commands:
#       - echo Running npm install
#       - npm install
#       # - echo Running tests
#       # - npm run test
#   build:
#     commands:
#       - echo Build started on `date`
#       - npm run build
#   post_build:
#     commands:
#        # copy the contents of /build to S3
#       - aws s3 cp --recursive --acl public-read ./build s3://duclassdeploybucket/ 
#       # set the cache-control headers for index.html to prevent
#       # browser caching
#       - aws s3 cp --acl public-read --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://duclassdeploybucket/


# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  pre_build:
    commands:
      #installs dependencies into the node_modules/ directory
      - npm install
      #- npm run test
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling
      - npm run build
  post_build:
    commands:
      - aws s3 cp --recursive --acl public-read ./build s3://duclassdeploybucket/ 
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*